services:
  app_blue:
    #build:
    #  context: ./site_blue
    #  dockerfile: Dockerfile_blue
    #  no_cache: true
    container_name: node_blue
    image: blue_app:latest
    restart: unless-stopped
    environment:
      # Настройки для GREEN среды (новая версия)
      - APP_COLOR=BLUE
      - APP_VERSION=1.0
    ports:
      - "8081:3000" 
    depends_on:
      - mongodb
  
  app_green:
    #build:
    #  context: ./site_green
    #  dockerfile: Dockerfile_green
    #  no_cache: true
    container_name: node_green
    image: green_app:latest
    restart: unless-stopped
    environment:
      # Настройки для GREEN среды (новая версия)
      - APP_COLOR=GREEN
      - APP_VERSION=2.0
    ports:
      - "8082:3000" 
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db 
  
  nginx-proxy: # Сервис-маршрутизатор / Балансировщик нагрузки
    image: nginx:latest
    ports:
      - "80:80" # Публичный порт, куда будут обращаться пользователи
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # <--- КЛЮЧ: Файл конфигурации Nginx
    depends_on:
      - app_blue
      - app_green

#volumes:
#  mongo-data: 